version: '3.8'
 
services:
  database:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bookmarkDb
    ports:
      - "5001:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
     
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
 
volumes:
  pgdata:
  pgadmin: